name: Deploy and Test server

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v1

    - name: Build Docker image
      run: docker build -t server ./api

    - name: Run Docker container
      run: docker run -d --name server-container server

    - name: Wait for container to start
      run: sleep 10

    - name: Execute migrations
      run: docker exec server-container php artisan migrate

    - name: Execute seeders
      run: docker exec server-container php artisan db:seed

    - name: Run tests
      run: docker exec server-container php artisan test
